import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import githubLogo from "../../img/github-logo-64x.png";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <div className="flex min-w-screen justify-end m-5">
          <Link href="https://github.com/jonesmarquelle">
            <Image
              className="w-8 md:w-12 aspect-square" 
              src={githubLogo}
              alt="Github Link"
            />
          </Link>
        </div>
        <div className="flex flex-col items-center justify-center">
          <h1 className="text-5xl font-thin w-full text-center">Image-To-Ascii Generator</h1>
          <div className="w-screen max-h-screen flex flex-col md:flex-row gap-10 p-20">
            <div className="flex flex-col w-full items-center">
                <label className="flex w-full lg:w-3/4 aspect-square text-3xl rounded-xl text-center justify-center items-center p-4 border-slate-400 border-4 border-dashed cursor-pointer">
                  <input className="hidden" type="file"/>
                  Select Image
                </label>
            </div>
            
            <div className="flex min-w-fit items-center justify-center">
            <button className="text-3xl font-thin rounded-xl text-center bg-indigo-800 px-5 py-1">
              Convert File
            </button>
            </div>
            
            <div className="flex flex-col w-full items-center">
                <h3 className="flex w-full lg:w-3/4 aspect-square text-3xl rounded-xl text-center justify-center items-center p-4 border-slate-400 border-4 border-dashed">
                  Output Image
                </h3>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
